Settings service and view
thomas-brunton/angular-tabletop-campaign-manager pull request #44
Opened 2020-10-15 17:39 UTC by thomas-brunton

2020-10-15 17:41 UTC, thomas-brunton commented
@Tsz-Fung-Ryan It will fail the travis build for code coverage because the table detail component has not been reworked yet so it doesn't have enough unit tests to get over the 90% threshold.

But if you find any other bugs or issues I will need to fix those.

2020-10-19 23:47 UTC, Tsz-Fung-Ryan commented on src/app/table/table-detail/table-detail.component.ts
> +      console.log('Cancelling detail view request since the component randomly sends requests with an undefined url, SHIT\'S FUCKED YO');
please remove the console comment

2020-10-19 23:48 UTC, Tsz-Fung-Ryan requested changes
Please resolve issues outlined in the code comments

2020-10-19 23:51 UTC, thomas-brunton commented on src/app/table/table-detail/table-detail.component.ts
> +      console.log('Cancelling detail view request since the component randomly sends requests with an undefined url, SHIT\'S FUCKED YO');
Fixed

2020-10-19 23:56 UTC, Tsz-Fung-Ryan commented
Change reviewed and issue outlined resolved

2020-10-19 23:56 UTC, merged